apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
spec:
  mtls:
    mode: STRICT


    # STRICT : 모든 통신은 mTLS로 해야함.
    # PERMISSIVE : mTLS와 일반 통신 모두 허용.